In [54]:
from pathlib import Path
import pandas as pd

# '..' means "go up one folder" to the project root
data_path = Path("..") / "data" / "output.csv"

# Load your df
df = pd.read_csv(data_path)

In [55]:
df.head()

,id,condition,valence,uncertainty,resolution,first_sentence,second_sentence,sentiment_1,valence_1,sentiment_2,valence_2,pair_uncertainty,pair_resolution
0,1,PosHghNoUnc,positive,low,low,Leo a commandé un écran sur Amazon.,Il reçoit son colis après 2 jours ouvrables co...,0.0,0.5,0.0,0.70,0.8,0.0
1,2,PosHghNoUnc,positive,low,low,Jade se balade avec une amie.,Elles parlent de leur journée.,0.3,0.6,0.4,0.70,0.1,0.0
2,3,PosHghNoUnc,positive,low,low,Sam est sur Tinder.,Il croise des profils différents et décide s'i...,0.0,0.3,0.1,0.40,0.8,0.0
3,4,PosHghNoUnc,positive,low,low,"Dernièrement, John suit un régime alimentaire ...",Il se sent en meilleure santé et il a perdu 3 kg.,0.0,0.3,0.7,0.90,0.1,0.5
4,5,PosHghNoUnc,positive,low,low,Lisa a travaillé assidûment pour sa thèse de m...,Elle a eu une très bonne note: 85%!.,0.7,0.9,0.9,0.95,0.3,0.8

In [ ]:
df_an = df.copy()

df_an["valence"] = df_an["valence"].apply(lambda x: 1 if x == "positive" else 0 if x == "negative" else pd.NA)
df_an["uncertainty"] = df_an["uncertainty"].apply(lambda x: 1 if x == "high" else 0 if x == "low" else pd.NA)
df_an["resolution"] = df_an["resolution"].apply(lambda x: 1 if x == "high" else 0 if x == "low" else pd.NA)

df_an["sentiment_1"] = df_an["sentiment_1"].apply(lambda x: 1 if x > 0 else 0 if x < 0 else pd.NA)
df_an["sentiment_2"] = df_an["sentiment_2"].apply(lambda x: 1 if x > 0 else 0 if x < 0 else pd.NA)

df_an["valence_1"] = df_an["valence_1"].apply(lambda x: 1 if x > 0.5 else 0 if x < 0.5 else pd.NA)
df_an["valence_2"] = df_an["valence_2"].apply(lambda x: 1 if x > 0.5 else 0 if x < 0.5 else pd.NA)

df_an["pair_uncertainty"] = df_an["pair_uncertainty"].apply(lambda x: 1 if x > 0.5 else 0 if x < 0.5 else pd.NA)
df_an["pair_resolution"] = df_an["pair_resolution"].apply(lambda x: 1 if x > 0.5 else 0 if x < 0.5 else pd.NA)

SyntaxError: expected 'else' after 'if' expression (2117619755.py, line 3)

In [57]:
df_an.head()

,id,condition,valence,uncertainty,resolution,first_sentence,second_sentence,sentiment_1,valence_1,sentiment_2,valence_2,pair_uncertainty,pair_resolution
0,1,PosHghNoUnc,1,0,0,Leo a commandé un écran sur Amazon.,Il reçoit son colis après 2 jours ouvrables co...,<NA>,<NA>,<NA>,1,1,0
1,2,PosHghNoUnc,1,0,0,Jade se balade avec une amie.,Elles parlent de leur journée.,1,1,1,1,0,0
2,3,PosHghNoUnc,1,0,0,Sam est sur Tinder.,Il croise des profils différents et décide s'i...,<NA>,0,1,0,1,0
3,4,PosHghNoUnc,1,0,0,"Dernièrement, John suit un régime alimentaire ...",Il se sent en meilleure santé et il a perdu 3 kg.,<NA>,0,1,1,0,<NA>
4,5,PosHghNoUnc,1,0,0,Lisa a travaillé assidûment pour sa thèse de m...,Elle a eu une très bonne note: 85%!.,1,1,1,1,0,1

In [58]:
df_an["valence_1"].value_counts()

valence_1
1    94
0    57
Name: count, dtype: int64

# F1 scores

In [ ]:
from sklearn import metrics

CONDITION = "valence"

df_filtered = df_an[df_an[f"{CONDITION}_1"].notna() & df_an[CONDITION].notna()]

df_filtered[f"{CONDITION}_1"].value_counts()

# metrics.f1_score(df_filtered[CONDITION], df_filtered[f"{CONDITION}_1"], average="binary")

valence_1
1    94
0    57
Name: count, dtype: int64

In [64]:
print(df_filtered[CONDITION].unique())
print(df_filtered[CONDITION].dtype)
print(df_filtered[f"{CONDITION}_1"].unique())
print(df_filtered[f"{CONDITION}_1"].dtype)

[1 0]
int64
[<NA> 1 0]
object